server:
  port: 8081

spring:
  application:
    name: service-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/dhy?useUnicode=true&characterEncoding=utf-8
    username: root


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/


  instance:
    lease-renewal-interval-in-seconds: 1

    lease-expiration-duration-in-seconds: 2

mybatis:
  config-locations: classpath:mybatis/confg.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.jk.model


